name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write # Needed to create releases and update files
  pull-requests: write # Needed to create Release PRs
  issues: write # Needed to create labels https://github.com/googleapis/release-please-action/issues/1105#issuecomment-2780292262

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Check if a new release was created for components-versions
        if: ${{ steps.release.outputs.components-versions_release_created }}
        run: |
          echo "Release created for components-versions: ${{ steps.release.outputs.components-versions_tag_name }}"
          echo "Release body for components-versions:"
          echo "${{ steps.release.outputs.components-versions_release_body }}"
